# Generated by Django 3.0.6 on 2021-06-09 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(auto_now=True)),
                ('consumed', models.BooleanField(default=False)),
                ('use_case', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reset Request',
                'verbose_name_plural': 'Reset Requests',
            },
        ),
        migrations.CreateModel(
            name='OtherRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_type', models.CharField(max_length=100)),
                ('details', models.CharField(default=None, max_length=254, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Other Request',
                'verbose_name_plural': 'Other Requests',
            },
        ),
        migrations.CreateModel(
            name='LoginLogoutFail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(default='Non-Mobile', max_length=254)),
                ('login', models.BooleanField(default=False)),
                ('login_time', models.DateTimeField(default=None, null=True)),
                ('logout', models.BooleanField(default=False)),
                ('logout_time', models.DateTimeField(default=None, null=True)),
                ('failed_login', models.BooleanField(default=False)),
                ('failed_login_time', models.DateTimeField(default=None, null=True)),
                ('message', models.TextField(default=None, null=True)),
                ('spare0', models.CharField(default=None, max_length=100, null=True)),
                ('spare1', models.CharField(default=None, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LoginLogoutFailures',
                'verbose_name_plural': 'LoginLogoutFailures',
            },
        ),
        migrations.CreateModel(
            name='DeviceId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_type', models.CharField(default='Android', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('deactivate_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device ID',
                'verbose_name_plural': 'Device IDs',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(default='Android', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('spare', models.CharField(default=None, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
