# Generated by Django 3.0.6 on 2021-06-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contactus_deviceid_loginlogoutfail_otherrequests_resetrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
