# Generated by Django 3.0.6 on 2021-06-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210618_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_downvotes',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total_upvotes',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
