# Generated by Django 3.0.6 on 2021-06-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210618_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='ts_rank',
            field=models.IntegerField(default=0),
        ),
    ]
