# Generated by Django 3.0.6 on 2021-06-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20210618_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='total_answers',
            field=models.IntegerField(default=0),
        ),
    ]
