# Generated by Django 3.0.6 on 2021-06-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20210618_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='down',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vote',
            name='up',
            field=models.BooleanField(default=False),
        ),
    ]
