# Generated by Django 3.0.6 on 2021-06-20 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20210618_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='in_reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='questions.Answer'),
        ),
    ]
